gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
copy $(DEPENDS) $(TARGET)
ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc $(DEPENDS) $(LIBS) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)
gcc $(DEPENDS) $(LIBS) -o $(TARGET)
gcc -c $(CFLAGS)  $(INPUT) -o $(TARGET)

