ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
ar rcu $(TARGET) $(DEPENDS) && ranlib $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ $(DEPENDS) $(LIBS) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ $(DEPENDS) $(LIBS) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ $(DEPENDS) $(LIBS) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ $(DEPENDS) $(LIBS) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)
g++ $(DEPENDS) $(LIBS) -o $(TARGET)
g++ -c $(CFLAGS)  $(INPUT) -o $(TARGET)

