/* code automatically generated by bin2c -- DO NOT EDIT */
{
/* #include'ing this file in a C program is equivalent to calling
  if (luaL_loadfile(L,"modules\\test.lua")==0) lua_pcall(L, 0, 0, 0); 
*/
/* modules\test.lua */
static const unsigned char B1[]={
114,101,116,117,114,110, 32,123, 13, 10,  9, 78, 65, 77, 69, 32, 61, 32, 34, 76,
 97,110, 99,101,108,111,116, 34, 59, 13, 10,  9, 81, 85, 69, 83, 84, 32, 61, 32,
 34, 84,111, 32,102,105,110,100, 32,116,104,101, 32, 72,111,108,121, 32, 71,114,
 97,105,108, 34, 59, 13, 10,  9, 70, 65, 86, 79, 82, 73, 84, 69, 95, 67, 79, 76,
 79, 82, 32, 61, 32, 34, 66,108,117,101, 34, 59, 13, 10,125,
};

 if (luaL_loadbuffer(L,(const char*)B1,sizeof(B1),"modules\\test.lua")==0) lua_pcall(L, 0, 1, 0);
}
